---
version: 2

project_name: archive-gmail

before:
  hooks:
    - go mod tidy
    - go test ./... -v

builds:
  ## Main app
  - id: archive-gmail
    env:
      - CGO_ENABLED=0
    main: ./cmd/archive-gmail
    binary: archive-gmail
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{ .CommitDate }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  ## OAuth2 auth CLI
  - id: archive-gmail-auth
    env:
      - CGO_ENABLED=0
    main: ./cmd/authenticate
    binary: archive-gmail-auth
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{ .CommitDate }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      _v{{ .Version }}
    files:
      - LICENSE*
      - README*

  - id: windows
    format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      _v{{ .Version }}
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "Merge pull request"
      - "Merge branch"
